version: 0.2
env:
  variables:
    S3_BUCKET: "cc-hw3-b1"
phases:
  pre_build:
    commands:
      - echo Copying files to S3 bucket
  build:
    commands:
      - aws s3 cp . s3://${S3_BUCKET} --recursive
artifacts:
  files:
    - '**/*'
  discard-paths: yes
